name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser(s) to run tests on'
        required: true
        default: 'single-desktop'
        type: choice
        options:
          - single-desktop
          - multiple-desktop
          - iphone-13
          - galaxy-s9
          - combination

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install default browsers (Chromium, WebKit, Firefox)
        if: ${{ github.event.inputs.browser == 'multiple-desktop' || github.event.inputs.browser == 'combination' }}
        run: playwright install --with-deps chromium webkit firefox

      - name: Install Chromium
        if: ${{ github.event.inputs.browser == 'single-desktop' || github.event.inputs.browser == 'combination' }}
        run: playwright install --with-deps chromium

      - name: Install WebKit for iPhone 13
        if: ${{ github.event.inputs.browser == 'iphone-13' || github.event.inputs.browser == 'combination' }}
        run: playwright install --with-deps chromium

      - name: Install Chromium for Galaxy S9+
        if: ${{ github.event.inputs.browser == 'galaxy-s9' || github.event.inputs.browser == 'combination' }}
        run: playwright install --with-deps chromium

      - name: Run tests on Chromium
        if: ${{ github.event.inputs.browser == 'single-desktop' || github.event.inputs.browser == 'combination' }}
        run: pytest --tracing=retain-on-failure --browser chromium

      - name: Run tests on WebKit and Firefox
        if: ${{ github.event.inputs.browser == 'multiple-desktop' || github.event.inputs.browser == 'combination' }}
        run: |
          pytest --tracing=retain-on-failure --browser webkit
          pytest --tracing=retain-on-failure --browser firefox

      - name: Run tests on iPhone 13
        if: ${{ github.event.inputs.browser == 'iphone-13' || github.event.inputs.browser == 'combination' }}
        run: pytest --tracing=retain-on-failure --device="iPhone 13"

      - name: Run tests on Galaxy S9+
        if: ${{ github.event.inputs.browser == 'galaxy-s9' || github.event.inputs.browser == 'combination' }}
        run: pytest --tracing=retain-on-failure --device="Galaxy S9+"

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/
