name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: true
        default: 'web'
        type: choice
        options:
          - api
          - web
          - both
          - all browsers
          - all browsers and api
      browser:
        description: 'Browser to run web tests on (required for web tests)'
        required: false
        default: 'chromium'
        type: choice
        options:
          - chromium
          - webkit
          - firefox

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      DEV_API_URL: ${{ secrets.DEV_API_URL }}
      DEV_CLIENT: ${{ secrets.DEV_CLIENT }}
      DEV_DB: ${{ secrets.DEV_DB }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Install Playwright Browsers
        run: playwright install --with-deps

      - name: Run Tests
        run: |
          pytest --alluredir=allure-results

      - name: Install Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.22.3/allure-2.22.3.tgz
          tar -xzf allure-2.22.3.tgz
          export PATH=$PATH:$PWD/allure-2.22.3/bin

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
