name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: true
        default: 'web'
        type: choice
        options:
          - api
          - web
          - both
      browser:
        description: 'Browser to run web tests on (required for web tests)'
        required: false
        default: 'chromium'
        type: choice
        options:
          - chromium
          - webkit
          - firefox

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      DEV_API_URL: ${{ secrets.DEV_API_URL }}
      DEV_CLIENT: ${{ secrets.DEV_CLIENT }}
      DEV_DB: ${{ secrets.DEV_DB }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html

      - name: Install Browser
        if: ${{ github.event.inputs.test_type == 'web' || github.event.inputs.test_type == 'both' }}
        run: playwright install --with-deps ${{ github.event.inputs.browser }}

      - name: Run API tests
        if: ${{ github.event.inputs.test_type == 'api' || github.event.inputs.test_type == 'both' }}
        run: |
          pytest -m apitest

      - name: Run Web tests
        if: ${{ github.event.inputs.test_type == 'web' || github.event.inputs.test_type == 'both' }}
        run: |
          pytest -m webtest --browser ${{ github.event.inputs.browser }}

#      - name: Upload Test Results
#        uses: actions/upload-artifact@v4
#        if: always()
#        with:
#          name: test-results
#          path: ${{ github.workspace }}/test-results/
