name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser or device to run tests on'
        required: true
        default: 'browser-chromium'
        type: choice
        options:
          - browser-chromium
          - browser-webkit
          - browser-firefox
          - iphone-13
          - galaxy-s9

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html

      - name: Install Chromium
        if: ${{ github.event.inputs.browser == 'browser-chromium' }}
        run: playwright install --with-deps chromium

      - name: Install WebKit
        if: ${{ github.event.inputs.browser == 'browser-webkit' }}
        run: playwright install --with-deps webkit

      - name: Install Firefox
        if: ${{ github.event.inputs.browser == 'browser-firefox' }}
        run: playwright install --with-deps firefox

      - name: Run tests on Chromium
        if: ${{ github.event.inputs.browser == 'browser-chromium' }}
        run: pytest -m web --browser chromium --html=test-results/report.html --self-contained-html

      - name: Run tests on WebKit
        if: ${{ github.event.inputs.browser == 'browser-webkit' }}
        run: pytest -m web --browser webkit --html=test-results/report.html --self-contained-html

      - name: Run tests on Firefox
        if: ${{ github.event.inputs.browser == 'browser-firefox' }}
        run: pytest -m web --browser firefox --html=test-results/report.html --self-contained-html

      - name: Upload Playwright traces and HTML report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces-and-report
          path: test-results/
