name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target to run tests on'
        required: true
        default: 'single-desktop'
        type: choice
        options:
          - single-desktop
          - multiple-desktop
          - single-mobile
          - multiple-mobile
          - combination

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure browsers are installed
        run: |
          case "${{ github.event.inputs.target }}" in
            "multiple-desktop")
              python -m playwright install --with-deps chromium webkit firefox
              ;;
            "single-mobile"|"multiple-mobile"|"combination")
              python -m playwright install --with-deps chromium webkit firefox
              ;;
            *)
              python -m playwright install --with-deps chromium
              ;;
          esac

      - name: Run your tests
        run: |
          case "${{ github.event.inputs.target }}" in
            "multiple-desktop")
              pytest --tracing=retain-on-failure --browser webkit
              pytest --tracing=retain-on-failure --browser firefox
              pytest --tracing=retain-on-failure --browser chromium
              ;;
            "single-mobile")
              pytest --tracing=retain-on-failure --browser 'chromium:emulator=Pixel 5'
              ;;
            "multiple-mobile")
              pytest --tracing=retain-on-failure --browser 'webkit:emulator=iPhone 13'
              pytest --tracing=retain-on-failure --browser 'chromium:emulator=Pixel 5'
              ;;
            "combination")
              pytest --tracing=retain-on-failure --browser webkit
              pytest --tracing=retain-on-failure --browser firefox
              pytest --tracing=retain-on-failure --browser chromium
              pytest --tracing=retain-on-failure --browser 'webkit:emulator=iPhone 13'
              pytest --tracing=retain-on-failure --browser 'chromium:emulator=Pixel 5'
              ;;
            *)
              pytest --tracing=retain-on-failure --browser chromium
              ;;
          esac

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/
