name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser(s) to run tests on'
        required: true
        default: 'single'
        type: choice
        options:
          - single
          - multiple

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure browsers are installed
        run: |
          if [[ "${{ github.event.inputs.browser }}" == 'multiple' ]]; then
            python -m playwright install --with-deps chromium webkit
          else
            python -m playwright install --with-deps chromium
          fi

      - name: Run your tests
        run: |
          if [[ "${{ github.event.inputs.browser }}" == 'multiple' ]]; then
            pytest --tracing=retain-on-failure --browser webkit
          fi
          pytest --tracing=retain-on-failure --browser chromium

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/
